### ISSUE TITLE
能否提供数据集准备教程及训练时的注意事项与心得？

### ISSUE THREAD

**Issue by DLSeed** [PlayVoice/lora-svc#23]
感谢大神将SVC往LoRA方向带！提两个建议：
1.能否提供一个数据集准备的简易教程，即从收集到的原始音频开始，如何一步步处理为符合训练要求的多个npy文件？
2.能否提供一些训练时的主意事项和心得？比如目前需要多少训练数据、数据质量上的要求、需要训练多久、如何判断训练已经完成、能否在56歌声模型上继续训练等

**Comment by MaxMax2016** [comment]
很抱歉呢，这个项目还没完成，完成后会逐步完善相关资料。

**Comment by DLSeed** [comment]
谢谢，已经按教程试成功了，转换效果不错！大神后续有没有将采样率提高到32K、44K的计划？

**Comment by MaxMax2016** [comment]
更高采样率应该不会。但会尝试更大的16k模型，期望更干净的音质。
