### ISSUE TITLE
Error when trying to infer a file

### ISSUE THREAD

**Issue by Desuka-art** [PlayVoice/lora-svc#24]
![cmd_MDH2J7FQW0](https://user-images.githubusercontent.com/111822082/229018173-e2750855-2561-46fb-92fa-a17acd6b177c.png)

**Comment by MaxMax2016** [comment]
maybe crepre can only input single channel 16KHz wave

**Comment by Desuka-art** [comment]
So what do I do? Make the audio file one channel? How do I do that?

**Comment by MaxMax2016** [comment]
yes,or change pit = compute_f0_nn(args.wave, device) to pit = compute_f0(args.wave)
https://github.com/PlayVoice/lora-svc/blob/main/svc_inference.py#L88

**Comment by Desuka-art** [comment]
Also, how do I get rid of the reverb for the output? Or is it only possible to infer with the reverb?

**Comment by MaxMax2016** [comment]
https://github.com/PlayVoice/lora-svc/blob/main/svc_inference.py#L112 mask this line
