### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by justinjohn0306** [PlayVoice/lora-svc#25]
What does this mean?

![Capture](https://user-images.githubusercontent.com/34035011/229043526-be85c7fd-d515-4fa0-880f-7b66b8371149.PNG)

**Comment by MaxMax2016** [comment]
your ppg maybe have some error, the ppg from whisper medium.pt is 1024D

**Comment by justinjohn0306** [comment]
yes, i'm using the large-v2 model so that might be the issue.

**Comment by justinjohn0306** [comment]
Yep, switching back to the medium.pt model fixed the issue

![Capture](https://user-images.githubusercontent.com/34035011/229047469-6ae9f1d3-a873-496b-ae13-5543606d3fc2.PNG)
