### ISSUE TITLE
您好，请问混响怎么去掉？

### ISSUE THREAD

**Issue by qiuyuzhao** [PlayVoice/lora-svc#27]
推理出来的声音又混响，请问混响在哪里能去掉？

**Comment by MaxMax2016** [comment]
https://github.com/PlayVoice/lora-svc/blob/main/svc_inference.py#L112 mask this line

**Comment by qiuyuzhao** [comment]
> [https://github.com/PlayVoice/lora-svc/blob/main/svc_inference.py#L112 屏蔽](https://github.com/PlayVoice/lora-svc/blob/main/svc_inference.py#L112%C2%A0mask)此行

 请问是这个么audio = svc_reverb(audio)，112行什么都没有。为什么推理出来的结果听着有一点沙哑

**Comment by MaxMax2016** [comment]
https://github.com/PlayVoice/lora-svc/blob/main/svc_inference.py#L133 mask this line 抱歉，昨天改过代码，行数变了

**Comment by qiuyuzhao** [comment]
> 

谢谢您，请问推理出来的声音有点沙哑，这个怎样能优化呢？
