### ISSUE TITLE
在已经完成一定训练后如何继续训练

### ISSUE THREAD

**Issue by xiank1** [PlayVoice/lora-svc#38]
如题

**Comment by MaxMax2016** [comment]
util/train. py 79行开始屏蔽的代码打开，启动训练的预训练模型指定为已训练过一段时间的模型

**Comment by MaxMax2016** [comment]
拉取最新代码：

从release页面下载预训练模型**maxgan_pretrain_5L.pth**，放到model_pretrain文件夹中，预训练模型中包含了生成器和判别器

    https://github.com/PlayVoice/lora-svc/blob/622fafca87d877a89717aeb09337afbadd885941/config/maxgan.yaml#L17

    > python svc_trainer.py -c config/maxgan.yaml -n lora
    
    恢复训练
    
    > python svc_trainer.py -c config/maxgan.yaml -n lora -p chkpt/lora/***.pth

**Comment by xiank1** [comment]
十分感谢
