### ISSUE TITLE
Missing speaker file

### ISSUE THREAD

**Issue by diiogofernands** [PlayVoice/lora-svc#40]
For the inference on the lora-svc-for-pretrain branch, we need the singer's speakers file,

`python svc_inference.py --config config/maxgan.yaml --model maxgan_g.pth --spk ./config/singers/singer0001.npy --wave test.wav`

How we can generate this files? (./config/singers/singer0001.npy )

**Comment by MaxMax2016** [comment]
https://github.com/PlayVoice/lora-svc/tree/main/config/singers

this speaker files are from mulit-singer data, is the average of singer's audio timbres

https://github.com/PlayVoice/lora-svc/blob/main/svc_preprocess_speaker_lora.py#L13~L25
