### ISSUE TITLE
如果想训练更高采样率的预训练模型有参考的参数吗

### ISSUE THREAD

**Issue by KakaruHayate** [PlayVoice/lora-svc#41]
如题

**Comment by MaxMax2016** [comment]
@KakaruHayate 为了节约算例，我使用了16K模型训练48K模型，所以没用上面的参数

**Comment by KakaruHayate** [comment]
> @KakaruHayate 为了节约算例，我使用了16K模型训练48K模型，所以没用上面的参数

大概用了多少数据量？

**Comment by MaxMax2016** [comment]
56 singers of 50 hours singing data for 48K pretrain model
