### ISSUE TITLE
声音沙哑是怎么回事

### ISSUE THREAD

**Issue by syaofox** [PlayVoice/lora-svc#43]
推理出来的声音每一句尾音都沙哑，是哪里的问题？

**Comment by MaxMax2016** [comment]
有输入输出音频样例没？直接用预训练模型推理呢？

**Comment by syaofox** [comment]
这是输入输出样例
[样例.zip](https://github.com/PlayVoice/lora-svc/files/11267333/default.zip)

用预训练模型推也是一个情况

**Comment by syaofox** [comment]
[预训练模型推理结果.zip](https://github.com/PlayVoice/lora-svc/files/11267354/default.zip)

**Comment by MaxMax2016** [comment]
@syaofox 转语音啊~~~，预训练模型用的全歌声数据

**Comment by MaxMax2016** [comment]
@syaofox 你好，经分析发现您的测试音频是TTS和成音频，每句结尾出的F0本身就是糊的，然后现有的算法都检测不出对应的F0；如果要做话语的转换不推荐使用SVC的方案
![输入音频](https://user-images.githubusercontent.com/16432329/232964040-5bc33208-78f9-4498-b972-85d0badab467.png)

从图片可以看到结尾的F0是糊在一起的
