### ISSUE TITLE
执行频率扩展时遇到严重性能问题

### ISSUE THREAD

**Issue by fatinghenji** [PlayVoice/lora-svc#44]
在执行频率扩展时遇到了严重的性能问题，占用情况如下图所示：
![image](https://user-images.githubusercontent.com/37131177/233525540-7a21302e-a3fa-4209-87d2-92d86a0548cb.png)
吃掉了我20G+的内存，跑满cpu，在C盘疯狂读写，持续15min+未结束。
- 电脑配置及环境：
  - 处理器	        13th Gen Intel(R) Core(TM) i5-13600KF   3.50 GHz
  - 机带 RAM	32.0 GB (31.8 GB 可用)
  - 版本	Windows 11 专业版
  - 版本	22H2
  - 操作系统版本	22621.1555
  - pycharm + anacoda + python3.9

**Comment by MaxMax2016** [comment]
更新下代码：svc_bandex.py，重新试试呢
