### ISSUE TITLE
弱弱的问下，推理时如何能升降调。。。

### ISSUE THREAD

**Issue by krysof** [PlayVoice/lora-svc#47]
类似 -t 3 这种参数。。。

**Comment by MaxMax2016** [comment]
https://github.com/PlayVoice/lora-svc/blob/main/svc_inference.py#L89-L95 现在代码里面根据歌声的平均应该进行升降掉，还没弄那么多功能，您可以看看这段代码，或者等着更新

**Comment by krysof** [comment]
看来是能力范围之外了，坐等更新，加油~
